wandb_version: 1

portion_model:
  desc: null
  value:
    layer_sizes:
    - 512
    - 512
    dropout_rate: 0.1
    epochs: 200
    batch_size: 64
    eval_metric: r2
presence_model:
  desc: null
  value:
    encoder_sizes:
    - 512
    - 256
    - 128
    - 64
    decoder_sizes:
    - 64
    - 128
    - 256
    - 512
    latent_dim: 20
    dropout_rate: 0.1
    epochs: 1
    batch_size: 512
    learning_rate: 0.001
    alpha: 1
    eval_metric: f1
embedding_model:
  desc: null
  value:
    embedding_size: 32
    walk_length: 10
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.0
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701737685.678109
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 13
      - 15
      - 16
      - 23
      4: 3.9.18
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
