wandb_version: 1

layer_sizes:
  desc: null
  value:
  - 512
  - 512
dropout_rate:
  desc: null
  value: 0.1
epochs:
  desc: null
  value: 200
batch_size:
  desc: null
  value: 64
test_size:
  desc: null
  value: 0.15
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.15.11
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700767618.1246
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 13
      - 15
      - 16
      - 23
      4: 3.10.13
      5: 0.15.11
      8:
      - 5
      13: linux-x86_64
